choco install 7zip -y
choco install adobereader -y
choco install ccleaner -y
choco install chefdk -y
choco install chocolatey -y
choco install ConEmu -y
choco install eclipse -y
choco install filezilla -y
choco install gimp -y
choco install git -y
choco install GoogleChrome -y
choco install hashcheck -y
choco install ie11 -y
choco install javaruntime -y
choco install jdk8 -y
choco install jre8 -y
choco install kdiff3 -y
choco install MicrosoftSecurityEssentials -y
choco install packer -y
choco install PowerShell -y
choco install procexp -y
choco install putty -y
choco install skype -y
choco install SublimeText3 -y
choco install synergy -y
choco install teamviewer -y
choco install telegram -y
choco install telegram.install -y
choco install vagrant -y
choco install vim -y
choco install virtualbox -y
choco install Wget -y
